### ISSUE TITLE
TypeError: exceptions must derive from BaseException

### ISSUE THREAD

**Issue by qingweihk** [Hangz-nju-cuhk/Talking-Face_PC-AVS#13]
Thanks for your great job.
I run bash experiments/demo_vox.sh and got an error:

Network [ResNeXtEncoder] was created. Total number of parameters: 38.0 million. To see the architecture, do print(network).
./checkpoints/demo/latest_net_G.pth not exists yet!
Traceback (most recent call last):
  File "inference.py", line 117, in <module>
    main()
  File "inference.py", line 97, in main
    model = create_model(opt).cuda()
  File "/content/Talking-Face_PC-AVS/models/__init__.py", line 33, in create_model
    instance = model(opt)
  File "/content/Talking-Face_PC-AVS/models/av_model.py", line 24, in __init__
    self.initialize_networks(opt)
  File "/content/Talking-Face_PC-AVS/models/av_model.py", line 272, in initialize_networks
    self.load_network(netG, 'G', opt.which_epoch)
  File "/content/Talking-Face_PC-AVS/models/av_model.py", line 773, in load_network
    raise ('Generator must exist!')
TypeError: exceptions must derive from BaseException.

Thanks

**Comment by Hangz-nju-cuhk** [comment]
Hi, the reason is that you have not put unzip the checkpoint file in the desired position thus the model cannot find the checkpoint pth.
