### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by CeccAnd** [Hangz-nju-cuhk/Talking-Face_PC-AVS#45]
Hello with bash experiments/demo_vox.sh I obtained an error:

~/Talking-Face_PC-AVS-main$ bash experiments/demo_vox.sh
Traceback (most recent call last):
  File "inference.py", line 4, in <module>
    from options.test_options import TestOptions
  File "/home/andrea/Talking-Face_PC-AVS-main/options/test_options.py", line 1, in <module>
    from .base_options import BaseOptions
  File "/home/andrea/Talking-Face_PC-AVS-main/options/base_options.py", line 5, in <module>
    from util import util
  File "/home/andrea/Talking-Face_PC-AVS-main/util/util.py", line 47
    imgs = np.concatenate([imgs, np.zeros((rowPadding, *imgs.shape[1:]), dtype=imgs.dtype)], axis=0)
                                                       ^
SyntaxError: invalid syntax

**Comment by etoscano** [comment]
I have the same error

I was just following the instructions to run the tool

**Comment by yuanbit** [comment]
I got the same error too, is there a solution?
